@extends('layouts.app')

@section('FrontContent')
    <div class="pt--100">
        <div class="container">
            <h1 style="box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:3rem;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;user-select:text !important;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Privacy Policy</strong></span>
            </h1>
            <p>
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );">Updated at 2023-09-03</span>
            </p>
            <p>
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );">AHS  is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by AHS.</span><br>
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );">This Privacy Policy applies to our website, http://ahsboardprep.com/, and its associated subdomains (collectively, our "Service"). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</span>
            </p>
            <h2 style="box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;user-select:text !important;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Definitions and key terms</strong></span>
            </h2>
            <p>
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );">To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</span><br>
            </p>
            <ul style="list-style-type:disc;">
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Cookie</strong>: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Company</strong>: when this policy mentions "Company," "we," "us," or "our," it refers to AHS Board Prep, USA that is responsible for your information under this Privacy Policy.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Country</strong>: where AHS or the owners/founders of AHS are based, in this case is USA.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Customer</strong>: refers to the company, organization or person that signs up to use the AHS Service to manage the relationships with your consumers or service users.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Device</strong>: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit AHS and use the services.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>IP address</strong>: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Personnel</strong>: refers to those individuals who are employed by AHS or are under contract to perform a service on behalf of one of the parties.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Personal Data</strong>: any information that directly, indirectly, or in connection with other information - including a personal identification number - allows for the identification or identifiability of a natural person.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Service</strong>: refers to the service provided by AHS as described in the relative terms (if available) and on this platform.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Third-party service</strong>: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</span>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>Website</strong>: AHS's site, which can be accessed via this URL: </span><a
                        target="_blank" rel="noopener noreferrer" href="http://ahsboardprep.com/."><span
                            style="color:hsl( 0, 0%, 0% );">http://ahsboardprep.com/.</span></a>
                </li>
                <li>
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><strong>You</strong>: a person or entity that is registered with AHS to use the Services.</span>
                </li>
            </ul>
            <div
                style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:300;letter-spacing:normal;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <h2 style="box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;user-select:text !important;">
                    <span style="color:hsl( 0, 0%, 0% );"><strong>What Information Do We Collect?</strong></span>
                </h2>
                <p class="p10"
                   style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;margin-bottom:1rem;margin-top:0px;user-select:text !important;">
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                                style="box-sizing:border-box;user-select:text !important;">We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</span></span>
                </p>
                <ul class="ul1"
                    style="box-sizing:border-box;margin-bottom:1rem;margin-top:0px;user-select:text !important;">
                    <li class="li11"
                        style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                        <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                    style="box-sizing:border-box;user-select:text !important;">Name / Username</span></span>
                    </li>
                    <li class="li11"
                        style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                        <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                    style="box-sizing:border-box;user-select:text !important;">Email Addresses</span></span>
                    </li>
                    <li class="li11"
                        style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                        <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                    style="box-sizing:border-box;user-select:text !important;">Debit/credit card numbers</span></span>
                    </li>
                    <li class="li11"
                        style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                        <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                    style="box-sizing:border-box;user-select:text !important;">Password</span></span>
                    </li>
                </ul>
            </div>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>How Do We Use The Information We Collect?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">Any of the information we collect from you may be used in one of the following ways:</span></span>
            </p>
            <ul class="ul1"
                style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:300;letter-spacing:normal;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <li class="li11"
                    style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                style="box-sizing:border-box;user-select:text !important;">To personalize your experience (your information helps us to better respond to your individual needs)</span></span>
                </li>
                <li class="li11"
                    style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                style="box-sizing:border-box;user-select:text !important;">To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)</span></span>
                </li>
                <li class="li11"
                    style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                style="box-sizing:border-box;user-select:text !important;">To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</span></span>
                </li>
                <li class="li11"
                    style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                style="box-sizing:border-box;user-select:text !important;">To process transactions</span></span>
                </li>
                <li class="li11"
                    style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                style="box-sizing:border-box;user-select:text !important;">To administer a contest, promotion, survey or other site feature</span></span>
                </li>
                <li class="li11"
                    style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                style="box-sizing:border-box;user-select:text !important;">To send periodic emails</span></span>
                </li>
            </ul>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span
                    style="color:hsl( 0, 0%, 0% );"><strong>When do we use customer information from third parties?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming our customer, we receive information from a third party that provides automated fraud detection services to us. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span
                    style="color:hsl( 0, 0%, 0% );"><strong>Do we share the information we collect with third parties?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.   </span></span><br>
                <br>
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through our service. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.   </span></span><br>
                <br>
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the service in a shared location, and type of device used to visit the service. They may aggregate information about our advertising and what you see on the service and then provide auditing, research and reporting for us and our advertisers.   </span></span><br>
                <br>
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Where and when is information collected from customers and end users?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>How Do We Use Your Email Address?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">By submitting your email address on our service, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span
                    style="color:hsl( 0, 0%, 0% );"><strong>Could my information be transferred to other countries?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We are incorporated in USA. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans- border transfer and hosting of such information.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span
                    style="color:hsl( 0, 0%, 0% );"><strong>Is the information collected through our service secure?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Can I update or correct my information?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">The rights you have to request updates or corrections to the information we collect depend on your relationship with us. Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times. You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable. If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Personnel</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">If you are one of our workers or applicants, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants. You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Sale of Business</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>How Long Do We Keep Your Information?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We keep your information only so long as we need it to provide service to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>How Do We Protect Your Information?</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Governing Law</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">The laws of USA, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Your Consent</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">By using our service, registering an account, or making a purchase, you consent to this Privacy Policy.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Links to Other Websites</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by us. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Remarketing Services</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're “following” people around the internet by serving ads on the websites and platforms they use most.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Payment Details</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Kids' Privacy</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from our servers.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Third-Party Services</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").</span></span>
            </p>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</span></span>
            </p>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</span></span>
            </p>
            <h2 style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(63, 69, 84); sans-serif;font-size:2.5rem;;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5rem;margin-top:20px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="color:hsl( 0, 0%, 0% );"><strong>Contact Us</strong></span>
            </h2>
            <p class="p10"
               style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;line-height:1.6;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s1"
                                                            style="box-sizing:border-box;user-select:text !important;">Don't hesitate to contact us if you have any questions.</span></span>
            </p>
            <ul class="ul1"
                style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(74, 80, 115); sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:300;letter-spacing:normal;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:left;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;user-select:text !important;white-space:normal;widows:2;word-spacing:0px;">
                <li class="li16"
                    style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                style="box-sizing:border-box;user-select:text !important;">Via Email: </span></span><a
                        style="background-color:transparent;box-sizing:border-box;color:inherit;text-decoration:none;transition:all 0.2s ease 0s;user-select:text !important;"><span
                            style="color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                  style="box-sizing:border-box;user-select:text !important;">info@ahsboardprep.com</span></span></a>
                </li>
                <li class="li16"
                    style="box-sizing:border-box; sans-serif;font-size:2rem;;font-weight:400;line-height:1.6;user-select:text !important;">
                    <span style="font-size:2rem;color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                style="box-sizing:border-box;user-select:text !important;">Via Phone Number: </span></span><a
                        style="background-color:transparent;box-sizing:border-box;color:inherit;text-decoration:none;transition:all 0.2s ease 0s;user-select:text !important;"><span
                            style="color:hsl( 0, 0%, 0% );"><span class="s3"
                                                                  style="box-sizing:border-box;user-select:text !important;">(631) 994-6616</span></span></a>
                </li>
            </ul>
        </div>
    </div>
@endsection
